language: ruby
cache: bundler
notifications:
  email: false
rvm:
  - 2.3
  - 2.4
  - 2.5
  - ruby-head
bundler_args: "--without development --retry=3 --jobs=3"
script: bundle exec rspec
deploy:
  provider: rubygems
  api_key:
    secure: tLRTsoCXlc73apqNCXoYUzipKSjyQ3+oJeifAEXlV33p9sjMVv0V6y1lxrKC6itGshbEnlGWl7e6Zq+/Hk/FGcrSsH68UXfH9HfZxOnZExpMp3wuECtB5/5vnz0iyVCnSZXDQd8p7Jp8n8wTAtcd0rxghO4/wh1/w0Qd7rPFsvwkX+PHf29rMVXAkOBTPinU2qnzXO56fb86CVA/x5LhVgJOUXxEDDGiiETuudxBjnIBBhTc2ctLKi2mMRUZMBGbfVBdT7XseJuq8zq+gLRoJRDTHLHzZm3eiudNa5dhCivFYdqOiUVQ3bE7DKmEW9TlmO7tYymFaF+VBGI7FFyq5mhF8wP9I0aundrD6fS7ZzqrTaFbGm4xgMlAgni6vGojqcGbbscmXJ+RdWsvaYhf8XqR8U/d7II5JGUtOaucvJ7GVp5VW3L4kpjnYKVCsmrhQUl1r4Zu8YO9s9IuUZPiAkPfJTVz3rqrIzk1zMj394F2r+OiULs2+o/bGUII6ACC57Wq5TuyPqQMeSywYcve6hFECNfh5Vs+wc/laqTcMyVzVs/0rhpjzGTFK2dF2LHgdHqxukjfKcnSqAlUPc489HUsz7jFY4wZjUTZJehHDzCxdJ80SK66J1W855EEkQDkRDHxc2+of+6o3IwALftTpFVd81zPlGsJ0dftCgSvJBQ=
  on:
    tags: true
